name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.5.8
        env:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: appointment
        options: "--health-cmd=\"mysqladmin ping\" --health-interval=10s --health-timeout=5s --health-retries=3"
        ports:
          - 3306:3306

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --prefer-dist --optimize-autoloader --no-ansi --no-interaction --no-scripts --no-progress
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Wait for MySQL to be ready
      run: until mysqladmin ping --host=127.0.0.1 --user=root --password=password --silent; do sleep 5; done
    - name: Run Database Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: appointment
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan migrate --force
    # - name: Run PHPUnit Tests
    #   env:
    #     DB_CONNECTION: mysql
    #     DB_HOST: 127.0.0.1
    #     DB_PORT: 3306
    #     DB_DATABASE: appointment
    #     DB_USERNAME: root
    #     DB_PASSWORD: password
      
